version: "3"

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: todo_db
    networks:
      springboot-mysql-net:

  todo-backend:
    image: mnurullaher/todoapp:1.0
    ports:
      - "8080:8080"
    environment:
      DB_PW: toor
      DB_USERNAME: root
      DB_URL: jdbc:mysql://mysql:3306/todo_db
    depends_on:
      - mysql
    networks:
      springboot-mysql-net:
    restart: on-failure

  todo-frontend:
    image: mnurullaher/todo-frontend:1.0
    ports:
      - 3000:80

networks:
  springboot-mysql-net: